language: common-lisp

sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash

script:
  - cl -l prove
       -e '(ql:quickload :cl-coveralls)'
       -e '(coveralls:with-coveralls (:exclude (list "t"))
             (prove:run :les-test))'
