language: common-lisp

sudo: required

env:
  matrix:
    - LISP=sbcl COVERALLS=true

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | bash
  - git clone https://github.com/fukamachi/cl-coveralls ~/lisp/cl-coveralls

script:
  - cl -e '(ql:quickload (list :prove
                               :cl-coveralls
                               :hunchentoot
                               :cl-who))'
       -e '(or (prove:run :les-test)
               (uiop:quit -1))'
       -e '(coveralls:with-coveralls (:exclude (list "t"))
             (ql:quickload :les))'
